name: CI/CD Backend Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/ci-cd
#      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzip-dev unzip
          sudo apt-get install -y php8.1-zip
          composer install

#  release:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to GitHub Container Registry
#        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
#
#      - name: Build and push Docker image
#        run: |
#          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/symfony-app:${{ github.sha }} .
#          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/symfony-app:${{ github.sha }}