name: CI/CD Backend Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/ci-cd
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzip-dev unzip
          sudo apt-get install -y php8.2-zip
          cp .env.build .env
          chmod +x symfony-scripts.sh
          composer install --no-interaction --optimize-autoloader --ignore-platform-reqs --prefer-dist --no-progress --no-suggest --no-scripts

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build -t ghcr.io/nsakkriou/${{ secrets.CI_REGISTRY_IMAGE }}:latest --platform linux/amd64,linux/arm64 --push .